import db_tools
db_tools.add_db_data("NYC", [1,2,3,4,5])
db_tools.add_db_data("NYC2", [1,2,4,5,5])
db_tools.add_db_data("NYC3", [1,243,42,53,5])
db_tools.add_db_data("NYC4", [12,43,42,53,52])
print(db_tools.get_db_data("NYC"))
print(db_tools.get_db_data("NYC2"))
boro_data = db_tools.get_random_data()
print(boro_data)
print(db_tools.get_random_boros(boro_data[1:]))